/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    Concept: typeof import('./src/components/Concept.vue')['default']
    ConceptElement: typeof import('./src/components/items/ConceptElement.vue')['default']
    ConceptStack: typeof import('./src/components/ConceptStack.vue')['default']
    DynamicSelectItem: typeof import('./src/components/items/DynamicSelectItem.vue')['default']
    GroupItem: typeof import('./src/components/items/GroupItem.vue')['default']
    HasManyItem: typeof import('./src/components/items/HasManyItem.vue')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IEpMoreFilled: typeof import('~icons/ep/more-filled')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IfItem: typeof import('./src/components/items/IfItem.vue')['default']
    ImageItem: typeof import('./src/components/items/ImageItem.vue')['default']
    ItemLabel: typeof import('./src/components/items/ItemLabel.vue')['default']
    NumberItem: typeof import('./src/components/items/NumberItem.vue')['default']
    SelectItem: typeof import('./src/components/items/SelectItem.vue')['default']
    SwitchItem: typeof import('./src/components/items/SwitchItem.vue')['default']
    TextItem: typeof import('./src/components/items/TextItem.vue')['default']
  }
}
